name: Push to Another Repository

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout source code
      uses: actions/checkout@v4

    - name: Configure Git
    - shell: bash
      env:
        HVLGITUSERNAME: ${{ secrets.HVLGITUSERNAME }}
        HVLGITPASS: ${{ secrets.HVLGITPASS }}
      run: |
        git config --global user.email "$HVLGITUSERNAME"
        git config --global user.name "$HVLGITPASS"
        
    - name: Push changes
    - shell: bash
      run: |
        git remote add hvlGit https://ider-database.westeurope.cloudapp.azure.com/Bonobo.Git.Server/
        git push hvlGit HEAD:main
